##################################################
# Name: labeler.yml
# Description: Configuration for Label workflow
##################################################

# Add 'documentation' label to markdown file changes
documentation:
  - docs/**
  - "*.md"

# Add 'rust' label to all rust file changes
rust:
  - "*.rs"
