##################################################
# Name: docker.yaml
# Description: Workflow to test containers with Docker
##################################################

name: Docker

on:

  push:
    branches:
      - trunk
    paths-ignore:
      - 'docs/**'
      - '**.md'

  pull_request:
    branches:
      - trunk
      - release/*
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - review_requested
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:

  PROJECT: ${{ github.repository }}

defaults:

  run:
    shell: bash

jobs:

  #########################
  # Perform basic container tests
  #########################

  test_container:

    name: Test Container

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:

      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v2

      - id: pull_request_source_dest_branch
        name: Pull request source and destination branch
        env:
          BRANCH_SOURCE: ${{ github.head_ref }}
          BRANCH_DEST: ${{ github.base_ref }}
        run: |
          echo "Pull Request Source: ${BRANCH_SOURCE}"
          echo "Pull Request Destination: ${BRANCH_DEST}"
        if: github.event_name == 'pull_request'

      - id: docker_build
        name: Docker Image Build
        run: >
          docker image build
          --rm
          --tag test:latest
          .

      - id: docker_test
        name: Docker Test Container
        run: >
          docker container run
          --rm
          --name test
          test:latest
