##################################################
# Name: linter.yaml
# Description: Workflow for the GitHub Super-Linter
##################################################

# Reference: https://github.com/github/super-linter

name: Linter

on:

  push:
    branches-ignore:
      - trunk

permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read
  checks: read
  deployments: read
  statuses: write

defaults:

  run:
    shell: bash

jobs:

  #########################
  # Run the GitHub Super-Linter
  ########################

  lint:

    name: GitHub Super-Linter

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:

      - id: checkout_repository
        name: Checkout repository with all history and tags
        uses: actions/checkout@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fetch-depth: 0
          submodules: false
          clean: true
          persist-credentials: true

      - id: run_linter
        name: Run GitHub Super Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          VALIDATE_DOCKER: true
          VALIDATE_MD: true
          VALIDATE_RUST: true
          VALIDATE_YAML: true
          ANSIBLE_DIRECTORY: "/ansible"
          ACTIONS_RUNNER_DEBUG: false
